services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: nome_utente
      POSTGRES_PASSWORD: nuova_password
      POSTGRES_DB: bike-db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - .:/app   # monta la cartella del progetto
    depends_on:
      - db

volumes:
  pgdata:
